"""Add_thoughts_table

Revision ID: f6f5d72b8f7c
Revises: 88e15c5eeb9c
Create Date: 2026-02-28 17:03:46.297658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f5d72b8f7c'
down_revision: Union[str, None] = '88e15c5eeb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_birthday_wishes_date', table_name='birthday_wishes')
    op.drop_index('ix_birthday_wishes_employee_id', table_name='birthday_wishes')
    op.drop_index('ix_birthday_wishes_sender_id', table_name='birthday_wishes')
    op.drop_table('birthday_wishes')
    op.drop_index('ix_leave_accrual_ledger_employee_id', table_name='leave_accrual_ledger')
    op.drop_index('ix_leave_accrual_ledger_year', table_name='leave_accrual_ledger')
    op.drop_table('leave_accrual_ledger')
    op.drop_index('ix_attendance_daily_user_date', table_name='attendance_daily')
    op.drop_table('attendance_daily')
    op.drop_index('ix_leave_balances_employee_id', table_name='leave_balances_old')
    op.drop_index('ix_leave_balances_id', table_name='leave_balances_old')
    op.drop_table('leave_balances_old')
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_index('ix_roles_role_rank', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_birthday_greetings_date', table_name='birthday_greetings')
    op.drop_index('ix_birthday_greetings_employee_id', table_name='birthday_greetings')
    op.drop_table('birthday_greetings')
    op.drop_constraint('uq_attendance_sessions_employee_work_date', 'attendance_sessions', type_='unique')
    op.alter_column('company_events', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'profile_photo_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_employees_work_mode', table_name='employees')
    op.alter_column('holidays', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('hr_policy_actions', 'meta_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('leave_balances', 'leave_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CL', 'PL', 'SL', 'RH', 'FL', 'COMPOFF', 'LWP', name='leavetype'),
               existing_nullable=False)
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.alter_column('leave_requests', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CANCELLED_BY_COMPANY', name='leavestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('leave_requests', 'auto_converted_to_lwp',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(None, 'leave_requests', 'employees', ['approver_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'employees', ['rejected_by_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'employees', ['cancelled_by_id'], ['id'])
    op.alter_column('leave_transactions', 'leave_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CL', 'PL', 'SL', 'RH', 'FL', 'COMPOFF', 'LWP', name='leavetype'),
               existing_nullable=False)
    op.create_index(op.f('ix_leave_transactions_action_by_employee_id'), 'leave_transactions', ['action_by_employee_id'], unique=False)
    op.create_index(op.f('ix_leave_transactions_id'), 'leave_transactions', ['id'], unique=False)
    op.alter_column('policy_settings', 'enforce_monthly_cap',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policy_settings', 'enforce_notice_days',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policy_settings', 'enforce_sick_intimation',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policy_settings', 'sandwich_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'sandwich_include_weekly_off',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'sandwich_include_holidays',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'sandwich_include_rh',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('policy_settings', 'treat_event_as_non_working_for_sandwich',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('policy_settings', 'allow_hr_override',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('restricted_holidays', 'active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restricted_holidays', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'allow_hr_override',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'treat_event_as_non_working_for_sandwich',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('policy_settings', 'sandwich_include_rh',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('policy_settings', 'sandwich_include_holidays',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'sandwich_include_weekly_off',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'sandwich_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('policy_settings', 'enforce_sick_intimation',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policy_settings', 'enforce_notice_days',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policy_settings', 'enforce_monthly_cap',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_leave_transactions_id'), table_name='leave_transactions')
    op.drop_index(op.f('ix_leave_transactions_action_by_employee_id'), table_name='leave_transactions')
    op.alter_column('leave_transactions', 'leave_type',
               existing_type=sa.Enum('CL', 'PL', 'SL', 'RH', 'FL', 'COMPOFF', 'LWP', name='leavetype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.alter_column('leave_requests', 'auto_converted_to_lwp',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('leave_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CANCELLED_BY_COMPANY', name='leavestatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.alter_column('leave_balances', 'leave_type',
               existing_type=sa.Enum('CL', 'PL', 'SL', 'RH', 'FL', 'COMPOFF', 'LWP', name='leavetype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('hr_policy_actions', 'meta_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('holidays', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_index('ix_employees_work_mode', 'employees', ['work_mode'], unique=False)
    op.alter_column('employees', 'profile_photo_updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('company_events', 'active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_unique_constraint('uq_attendance_sessions_employee_work_date', 'attendance_sessions', ['employee_id', 'work_date'])
    op.create_table('birthday_greetings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('greeting_image_url', sa.TEXT(), nullable=True),
    sa.Column('greeting_message', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('wish_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('wish_sent_by', sa.INTEGER(), nullable=True),
    sa.Column('wish_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['wish_sent_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date')
    )
    op.create_index('ix_birthday_greetings_employee_id', 'birthday_greetings', ['employee_id'], unique=False)
    op.create_index('ix_birthday_greetings_date', 'birthday_greetings', ['date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('wfh_enabled', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role_rank', sa.INTEGER(), server_default=sa.text('(99)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roles_role_rank', 'roles', ['role_rank'], unique=False)
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.create_table('leave_balances_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('cl_balance', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('sl_balance', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('pl_balance', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('rh_used', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_accrual_month', sa.VARCHAR(length=7), nullable=True),
    sa.Column('pl_carried_forward', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('pl_encash_days', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', name='uq_employee_year')
    )
    op.create_index('ix_leave_balances_id', 'leave_balances_old', ['id'], unique=False)
    op.create_index('ix_leave_balances_employee_id', 'leave_balances_old', ['employee_id'], unique=False)
    op.create_table('attendance_daily',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('work_date', sa.DATE(), nullable=False),
    sa.Column('first_in_time', sa.DATETIME(), nullable=True),
    sa.Column('is_good', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('computed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'work_date', name='pk_attendance_daily')
    )
    op.create_index('ix_attendance_daily_user_date', 'attendance_daily', ['user_id', 'work_date'], unique=False)
    op.create_table('leave_accrual_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('delta_days', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('action_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', 'leave_type', name='uq_accrual_emp_year_month_type')
    )
    op.create_index('ix_leave_accrual_ledger_year', 'leave_accrual_ledger', ['year'], unique=False)
    op.create_index('ix_leave_accrual_ledger_employee_id', 'leave_accrual_ledger', ['employee_id'], unique=False)
    op.create_table('birthday_wishes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reply_message', sa.TEXT(), nullable=True),
    sa.Column('replied_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_birthday_wishes_sender_id', 'birthday_wishes', ['sender_id'], unique=False)
    op.create_index('ix_birthday_wishes_employee_id', 'birthday_wishes', ['employee_id'], unique=False)
    op.create_index('ix_birthday_wishes_date', 'birthday_wishes', ['date'], unique=False)
    # ### end Alembic commands ###
